### ISSUE TITLE
Neighborhood Attention 3D

### ISSUE THREAD

**Issue by icerain-alt** [SHI-Labs/NATTEN#11]
Sorry, could you share the  Neighborhood Attention 3D (CUDA)?  ice_rain123@foxmail.com

**Comment by alihassanijr** [comment]
Hello and thank you for your interest.

Unfortunately we don't have a stable release for the 3D module yet.
I'll mark this as an enhancement and close it when we actually release it.

**Comment by btwbtm** [comment]
Hi, Is there any update for the 3D version? Thx!

**Comment by sheshap** [comment]
@alihassanijr Kindly let us know if any updates on 3D NA. Thanks in Advance.

**Comment by alihassanijr** [comment]
Thank you for your interest @sheshap @btwbtm @wenyihong @icerain-alt .

We will release an initial version of 3D NA this week.

**Comment by alihassanijr** [comment]
3D NA was just merged. We'll probably aim to push a new release some time soon, probably aligned with the next PyTorch release.

But for now, you can clone main and build from source and start using 3D!

**Comment by alihassanijr** [comment]
I'll close this issue for now. Feel free to reopen it if you have any questions or run into issues using 3D.
