### ISSUE TITLE
Natten 0.17.0 on MBP M1 Silicon

### ISSUE THREAD

**Issue by MrSutsuj** [SHI-Labs/NATTEN#140]
Hey Guys,

is there a way to install the latest version on MBP M1 Chips?
Tried many ways but unfortunatly couldn't figure it out.

Can you help me?

Tihank you so much, best regards!

**Comment by alihassanijr** [comment]
Please refer to https://shi-labs.com/natten/ and select your pytorch version, and install the CPU only build.

**Comment by gta191977649** [comment]
`       File "/opt/miniconda3/envs/Project-Outlier-Music/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
          assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
      AssertionError: would build wheel with unsupported tag ('cp310', 'cp310', 'macosx_14_0_arm64')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for natten
  Running setup.py clean for natten
Failed to build natten
`

**Comment by alihassanijr** [comment]
Actually you're right, I was mistaken before. Apple silicon users would need to install without wheels.
All wheels are x86_64.
Can you try just `pip install natten==0.17.1`? That should work.

**Comment by alihassanijr** [comment]
The issue appears to be resolved, so closing now. Feel free to reopen if you still have questions.
