### ISSUE TITLE
RuntimeError: Expected bias.shape[0] == heads.

### ISSUE THREAD

**Issue by justin4ai** [SHI-Labs/NATTEN#141]
Hello, I'm trying to use ```na1d_qk``` function of your package. I think my implementation well matches the forward function of ```NeighborhoodAttention1D``` class in [na1d.py](https://github.com/SHI-Labs/NATTEN/blob/main/src/natten/na1d.py) but ```RuntimeError: Expected bias.shape[0] == heads.``` occurs.

Actually this is a mimic of only a part of my code but at least it explains the situation.

```python

import math
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.init import trunc_normal_
import warnings
import sys

from natten.functional import na2d_av, na2d_qk, na1d_av, na1d_qk
from natten import (
    use_fused_na,
    use_autotuner
)
use_fused_na(True)
use_autotuner(True)



_q = torch.zeros(20, 2, 256, 64) # (Batch, num_heads, X, X)
_k = torch.zeros(20, 2, 256, 64) # (Batch, num_heads, X, X)
_rpb = torch.zeros(3, 13, 13)
_dilation = 1
_kernel_size = 7

z = na1d_qk(_q, _k, kernel_size=_kernel_size, dilation=_dilation, rpb=_rpb) # RuntimeError: Expected bias.shape[0] == heads.
#z = na1d_qk(_q.permute(0,2,1,3), _k.permute(0,2,1,3), kernel_size=_kernel_size, dilation=_dilation, rpb=_rpb) # RuntimeError: Input axes must be greater than or equal to the product of kernel size and dilation. Got kernel size 7, dilation 1, but dimension size was 2.

```

Although I carefully took a look into ```/natten-build/csrc/./include/natten/pytorch/helpers.h``` I still have no idea about ,,which part of my code'' triggered it. Would you mind explaining the reason?

Also I tried

```python

..
use_fused_na(False)
use_autotuner(False)
..
z = na1d_qk(_q.permute(0,2,1,3), _k.permute(0,2,1,3), kernel_size=_kernel_size, dilation=_dilation, rpb=_rpb)

```

Then another error ```RuntimeError: Input axes must be greater than or equal to the product of kernel size and dilation. Got kernel size 7, dilation 1, but dimension size was 2.``` occurs. Seemingly it is due to the wrong order of dimensions but I cannot understand since the permuted order looks corresponding to ```else``` case of the condition within the class in ``` [na1d.py](https://github.com/SHI-Labs/NATTEN/blob/main/src/natten/na1d.py)``` - please see from line 94.

Thanks for your dedicated amazing work, hopefully I can hear from you!

Best Regards,
Junyeong Ahn

**Comment by alihassanijr** [comment]
Thank you for your interest;

A couple of things:

1. You have 2 attention heads here:
```python3
_q = torch.zeros(20, 2, 256, 64)
```

But RPB is set to 3 attention heads, hence the mismatch:
```python3
_rpb = torch.zeros(3, 13, 13)
```

2. It looks like you're trying to use Fused Neighborhood Attention:
```python3
use_fused_na(True)
use_autotuner(True)
```

However, `na1d_qk` and `na1d_av` still correspond to the standard unfused implementation.

You'll need to import `na1d` from `natten.functional`, and pass QKV to it all together:

```python3
from natten.functional import na1d

output = na1d(q, k, v, kernel_size=kernel_size, dilation=dilation)
```

The only effect `use_fused_na` has is that it tells `NeighborhoodAttention1D` (and other modules) to [use `na1d` instead of `na1d_qk` + `softmax` + `na1d_av`, and to permute QKV differently](https://github.com/SHI-Labs/NATTEN/blob/main/src/natten/na1d.py#L94-L119).

You are correct in that the fused layout is different from unfused:

```python3
# Fused is "heads last"
# q/k/v.shape is [batch, seqlen, heads, head_dim]
output = na1d(q, k, v, kernel_size=kernel_size, dilation=dilation)

# Unfused is "heads first"
# q/k/v.shape is [batch, heads, seqlen, head_dim]
attn = na1d_qk(q, k, kernel_size=kernel_size, dilation=dilation)
attn = (attn * attn_scale).softmax(dim=-1)
output = na1d_av(attn, v, kernel_size=kernel_size, dilation=dilation)
```

For more information on transitioning from unfused neighborhood attention to fused, please refer to https://github.com/SHI-Labs/NATTEN/blob/main/docs/fna/fna-quickstart.md .

3. If you're using RPB, then you can't train with Fused Neighborhood Attention, since we're deprecating support for RPB.
That said, you can still run inference with Fused Neighborhood Attention and use RPB.

I hope this clarifies things for you, but if not, feel free to keep the issue open.

**Comment by justin4ai** [comment]
> Thank you for your interest;
> 
> A couple of things:
> 
> 1. You have 2 attention heads here:
> 
> ```python
> _q = torch.zeros(20, 2, 256, 64)
> ```
> 
> But RPB is set to 3 attention heads, hence the mismatch:
> 
> ```python
> _rpb = torch.zeros(3, 13, 13)
> ```
> 
>  2. It looks like you're trying to use Fused Neighborhood Attention:
> 
> ```python
> use_fused_na(True)
> use_autotuner(True)
> ```
> 
> However, `na1d_qk` and `na1d_av` still correspond to the standard unfused implementation.
> 
> You'll need to import `na1d` from `natten.functional`, and pass QKV to it all together:
> 
> ```python
> from natten.functional import na1d
> 
> output = na1d(q, k, v, kernel_size=kernel_size, dilation=dilation)
> ```
> 
> The only effect `use_fused_na` has is that it tells `NeighborhoodAttention1D` (and other modules) to [use `na1d` instead of `na1d_qk` + `softmax` + `na1d_av`, and to permute QKV differently](https://github.com/SHI-Labs/NATTEN/blob/main/src/natten/na1d.py#L94-L119).
> 
> You are correct in that the fused layout is different from unfused:
> 
> ```python
> # Fused is "heads last"
> # q/k/v.shape is [batch, seqlen, heads, head_dim]
> output = na1d(q, k, v, kernel_size=kernel_size, dilation=dilation)
> 
> # Unfused is "heads first"
> # q/k/v.shape is [batch, heads, seqlen, head_dim]
> attn = na1d_qk(q, k, kernel_size=kernel_size, dilation=dilation)
> attn = (attn * attn_scale).softmax(dim=-1)
> output = na1d_av(attn, v, kernel_size=kernel_size, dilation=dilation)
> ```
> 
> For more information on transitioning from unfused neighborhood attention to fused, please refer to https://github.com/SHI-Labs/NATTEN/blob/main/docs/fna/fna-quickstart.md .
> 
> 3. If you're using RPB, then you can't train with Fused Neighborhood Attention, since we're deprecating support for RPB.
>    That said, you can still run inference with Fused Neighborhood Attention and use RPB.
> 
> I hope this clarifies things for you, but if not, feel free to keep the issue open.

Thanks for your kind explanation. So the input axes error stems from the discrepancy between 2 and 3? I'll also try to use na1d function within an hour and give you back.

About RPB, what I want is to replace unmasked self attention with na module in GPT (transformer decoder), thus definitely I need to make it trainable. If I cannot use RPB for that goal, would you mind letting me know the alternatives?

Thanks,
Junyeong Ahn

**Comment by alihassanijr** [comment]
> So the input axes error stems from the discrepancy between 2 and 3? 

Yes exactly.

> About RPB, what I want is to replace unmasked self attention with na module in GPT (transformer decoder), thus definitely I need to make it trainable. If I cannot use RPB for that goal, would you mind letting me know the alternatives?

Rotary embeddings have typically been very successful, often outperforming RPB, and they are completely separate from the attention op, which makes it easier to pick different attention ops/implementations.
RPB is also a really bad bottleneck in the backward pass; the reduction is a nightmare and I've never been able to get a good enough version of it, and that is why it was not implemented in Fused Neighborhood Attention.

**Comment by justin4ai** [comment]
```python

import math
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.init import trunc_normal_
import warnings
import sys

from natten.functional import na2d_av, na2d_qk, na1d_av, na1d_qk, na1d
from natten import (
    use_fused_na,
    use_autotuner
)
use_fused_na(True)
use_autotuner(True)

torch.cuda.set_device("cuda:0")
print(torch.cuda.is_available())


_q = torch.zeros(20, 2, 256, 64) # (Batch, num_heads, X, X)
_k = torch.zeros(20, 2, 256, 64) # (Batch, num_heads, X, X)
_v = torch.zeros(20, 2, 256, 64) # (Batch, num_heads, X, X)
_rpb = torch.zeros(2, 13, 13)
_dilation = 1
_kernel_size = 7

x = na1d_qk(_q.permute(0,2,1,3), _k.permute(0,2,1,3), kernel_size=_kernel_size, dilation=_dilation, rpb=_rpb) # RuntimeError: Expected bias.shape[0] == heads.
#y = na1d(_q.permute(0,2,1,3), _k.permute(0,2,1,3), _v.permute(0,2,1,3), kernel_size=_kernel_size, dilation=_dilation, rpb=_rpb) # RuntimeError: Input axes must be greater than or equal to the product of kernel size and dilation. Got kernel size 7, dilation 1, but dimension size was 2.

```

I tried this code. According to your explanation, ```RuntimeError: Input axes must be greater than or equal to the product of kernel size and dilation. Got kernel size 7, dilation 1, but dimension size was 2.``` must be gone since now dimensions between qkv and rpb match (=2) but still occurs when printing ```x```out. Also I think it may be rather related to ```num_heads``` and ```kernel_size & dilation```   as it says, still have no clue about what ```input axes``` means though.

With the trial of using ```na1d``` function (variable ```y```) according to your suggestion, the following error occurs:

```

| 2024-06-07 10:45:20,871 | [[ natten.context ]] [ INFO ]: You're enabling the use of Fused Neighborhood Attention kernels. You can also consider enabling auto-tuning for potentially improved performance. Refer to the docs for more information.
| 2024-06-07 10:45:20,871 | [[ natten.context ]] [ WARNING ]: You're enabling NATTEN auto-tuner. This is an experimental feature intended only for fused neighborhood attention. Proceed with caution.
True
Traceback (most recent call last):
  File "tmp.py", line 30, in <module>
    y = na1d(_q.permute(0,2,1,3), _k.permute(0,2,1,3), _v.permute(0,2,1,3), kernel_size=_kernel_size, dilation=_dilation, rpb=_rpb) # RuntimeError: Input axes must be greater than or equal to the product of kernel size and dilation. Got kernel size 7, dilation 1, but dimension size was 2.
  File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/natten/functional.py", line 1700, in na1d
    tiling_config_forward, tiling_config_backward = autotune_fna(
  File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/natten/autotuner/__init__.py", line 223, in autotune_fna
    forward_pass_configs = get_all_tiling_configs_for_fna_forward(
  File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/natten/autotuner/fna_forward.py", line 100, in get_all_tiling_configs_for_fna_forward
    return _get_all_tiling_configs_for_fna_forward(
  File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/natten/autotuner/fna_forward.py", line 82, in _get_all_tiling_configs_for_fna_forward
    if get_device_cc(device) in [86, 89]:
  File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/natten/autotuner/misc.py", line 33, in get_device_cc
    major, minor = torch.cuda.get_device_capability(device_index)
  File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/torch/cuda/__init__.py", line 430, in get_device_capability
    prop = get_device_properties(device)
  File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/torch/cuda/__init__.py", line 445, in get_device_properties
    device = _get_device_index(device, optional=True)
  File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/torch/cuda/_utils.py", line 34, in _get_device_index
    raise ValueError(f"Expected a cuda device, but got: {device}")
ValueError: Expected a cuda device, but got: cpu

```

where my machine properly recognizes gpu 0 but the function does not.

By the ways, thanks for your information about embedding stuff! I've searched about it and am trying to find a solution with my implementation.

Best,
Junyeong Ahn

**Comment by alihassanijr** [comment]
1. The problem is still that you're permuting your inputs. Unfused inputs should be `[batch, heads, seqlen, dim]`. Input axes refers to `seqlen` in 1D, `height` and `width` in 2D, and `depth`, `height`, and `width` in 3D problems.

2. You should check your tensors and what devices they're on. It looks like `query` might be on cpu, and that's why auto-tuning fails. Although it should have caught that earlier on and raised a better error.
Can you print `query.device` and check?

3. Yes you can use some sort of a positional embedding which would be applied to attention inputs (typically just Q and K). We actually have a new preprint coming out soon about this, so stay tuned for that.

And I'm happy to help, feel free to ask as many questions as you'd like 🙂 .

**Comment by justin4ai** [comment]
> 1. The problem is still that you're permuting your inputs. Unfused inputs should be `[batch, heads, seqlen, dim]`. Input axes refers to `seqlen` in 1D, `height` and `width` in 2D, and `depth`, `height`, and `width` in 3D problems.
> 2. You should check your tensors and what devices they're on. It looks like `query` might be on cpu, and that's why auto-tuning fails. Although it should have caught that earlier on and raised a better error.
>    Can you print `query.device` and check?
> 3. Yes you can use some sort of a positional embedding which would be applied to attention inputs (typically just Q and K). We actually have a new preprint coming out soon about this, so stay tuned for that.
> 
> And I'm happy to help, feel free to ask as many questions as you'd like 🙂 .

I really appreciate your kind help! About **1.** and **2.**, I must have rushed too much under pressure ( ´•̥̥̥o•̥̥̥`). Those were completely due to my mistakes. About **3.**, I successfully implemented rotary embeddings to q and k (of course not to v).

Your quick help allowed me to implement the module Hydra-1D-NA! I really appreciate your help once again and am looking forward to meet your new preprint up soon. Love your amazing package. Thanks for providing such a brilliant project for the world.

Best Regards,
Junyeong Ahn

**Comment by justin4ai** [comment]
I close this issue since the problem is resolved.
