### ISSUE TITLE
Is it even possible to install natten on Windows?

### ISSUE THREAD

**Issue by adrianblazeusz** [SHI-Labs/NATTEN#147]
I have been struggling with installing natten on windows for a long time, I tried pip and mostly I got such errors

``746f69d0bd96e8085c4a5\setup.py", line 219, in build_extension
          subprocess.check_call(
        File "C:\Program Files\Python311\Lib\subprocess.py", line 413, in check_call      
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\adrian_b\\AppData\\Local\\Temp\\pip-install-g7udw0x_\\nattll-g7udw0x_\\natten_4a7e0e8d2a7746f69d0bd96e8085c4a5\\csrc', '-DPYTHON_PATH=C:\\Users\\adrian_b\\Desktop\\gendesign-main\\venverative-interior-design-main\\venv\\Scripts\\python.exe', '-DOUTPUT_FILE_NAME=natten\\libnatten.cp311-win_amd-DNATTEN_IS_WINDO64', '-DNATTEN_CUDA_ARCH_LIST=', '-DNATTEN_IS_WINDOWS=1', '-DNATTEN_IS_MAC=0', '-DIS_LIBTORCH_BUILT_WITH_CXX1Users\\adrian_b\\1_ABI=0', '-DNATTEN_WITH_AVX=1', '-DPY_LIB_DIR=C:\\Users\\adrian_b\\Desktop\\generative-interior-design-main\turned non-zero e\venv\\Scripts\\libs', '-G Ninja', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for natten
  Running setup.py clean for natten
Failed to build natten
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (natten)``

**Comment by alihassanijr** [comment]
Thanks for your interest. You should be able to build on Windows. If you're using WSL, the proccess is the same as installing on Linux with wheels.

If not, you need MSVC. Please refer to the instructions below for building NATTEN with MSVC:

https://github.com/SHI-Labs/NATTEN/blob/main/docs/install.md#Build-with-MSVC

**Comment by KangHyunwoogi** [comment]
Hello, alihassanijr,
I'm also having trouble building natten on Windows..., but my pytorch version is 1.11. Is there any solution to build natten in case of torch version 1.xx??

Thanks,

**Comment by adrianblazeusz** [comment]
OK, I used Vbox with Ubuntu and this type of command works: pip3 install natten==0.17.1+torch230cu121 -f https://shi-labs.com/natten/wheels

but ``pip install natten`` still has compilation problems. In most cases, `torch not found` even though torch is there from the very beginning and reinstalling does not help either.

**Comment by alihassanijr** [comment]
Sorry I'm confused -- `pip3 install natten==0.17.1+torch230cu121 -f https://shi-labs.com/natten/wheels` works?
Then what is the issue?

**Comment by adrianblazeusz** [comment]
Yes `pip3 install natten==0.17.1+torch230cu121 -f https://shi-labs.com/natten/wheels` works just fine.
If i try run `pip install natten` then library has problem with finding torch, but that's probably due to Windows

**Comment by alihassanijr** [comment]
`pip install natten` should work as well, but I can't really tell why the build process failed without seeing the full log.
I guess it is possible that some WSL instances might not have the cuda toolkit or compilation tools available.

But anyway, wheels are there so that users don't have to build / compile unless they choose to, and if that wasn't the case here and using wheels works, I guess we can close this issue.
