### ISSUE TITLE
shi-labs.com down?

### ISSUE THREAD

**Issue by donishi** [SHI-Labs/NATTEN#156]
Hi, it seems shi-labs.com is down today. `pip` is getting timeout errors, and the web page doesn't open on the browser either.
```
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after
connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection 
object at 0x7f1eeced1690>, 'Connection to shi-labs.com timed out. (connect timeout=15)')': /natten/wheels
```

Any estimate on when it will be back online? Or is there another mirror or any other way to install Natten until then?

**Comment by donishi** [comment]
OK, it's up now. I'll download the wheels locally to make sure I have it around. Closing the issue...

**Comment by alihassanijr** [comment]
I'm sorry; I was really busy this week and couldn't respond.

Unfortunately our (former) campus where the website was being hosted was doing an island mode test, and this was likely a result of that.

We'll soon mirror NATTEN binaries and possibly relocate our servers.

Apologies for the inconvenience.
