### ISSUE TITLE
NATTEN TO ONNX 

### ISSUE THREAD

**Issue by idanpd** [SHI-Labs/NATTEN#17]
Hi,
trying to convert to onnx but natten module can not be converted.
Is there any solution for this kind of problem ?

issue created when getting to:

_C.natten2dav_forward(
attn,
value,
dilation)

and other functions as well

**Comment by alihassanijr** [comment]
Thanks for bringing this up.
We're uncertain at this point whether or not we'd be able to support ONNX in the upcoming builds, but we'll keep this issue open until we come back to it.

**Comment by alihassanijr** [comment]
Closing this now.
I definitely won't have the bandwidth to add support for other engines (ONNX/TRT/etc).
I'm just not sure if we can even do torch compile without those engines supporting custom ops.
