### ISSUE TITLE
Can not access wheels url

### ISSUE THREAD

**Issue by Luciennnnnnn** [SHI-Labs/NATTEN#176]
Hi, I have tried to install nation from your wheels, however, it seems that url can not be accessed.

```bash
pip download natten==0.17.2+torch210cu118 -f https://shi-labs.com/natten/wheels
Looking in links: https://shi-labs.com/natten/wheels
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)'))': /natten/wheels
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)'))': /natten/wheels
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)'))': /natten/wheels
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)'))': /natten/wheels
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)'))': /natten/wheels
Could not fetch URL https://shi-labs.com/natten/wheels: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='shi-labs.com', port=443): Max retries exceeded with url: /natten/wheels (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)'))) - skipping
ERROR: Ignored the following yanked versions: 0.14.1
ERROR: Could not find a version that satisfies the requirement natten==0.17.2+torch210cu118 (from versions: 0.14.2.post4, 0.14.4, 0.14.5, 0.14.6, 0.15.0, 0.15.1, 0.17.0, 0.17.1, 0.17.2)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
ERROR: No matching distribution found for natten==0.17.2+torch210cu118
```

**Comment by alihassanijr** [comment]
Thank you for your interest, and apologies for the inconvenience. We're working on the issue and SSL should be back soon.

**Comment by Luciennnnnnn** [comment]
@alihassanijr currently, https://shi-labs.com/natten/ is also can not be accessed, hope to see it com back soon~

**Comment by alihassanijr** [comment]
Sorry yes our SSL certificate had to be reissued and it's taking a while to update it. Will update the thread once it's back up.

**Comment by alihassanijr** [comment]
It should be all back to normal; apologies for the inconvenience.

Could you or someone else give a thumbs up if this is fixed on their end?

**Comment by chenz97** [comment]
Not fixed by now.

**Comment by alihassanijr** [comment]
Thanks @chenz97 ; we had to make one last change and it should hopefully be back within the next 1-2 days.

**Comment by ONground-Korea** [comment]
@alihassanijr Hello, I am also experiencing difficulties with the installation due to the same issue. Could you please let me know when it might be possible to install it successfully? Is there an alternative method to install it other than using pip install?

**Comment by alihassanijr** [comment]
@ONground-Korea can you try and see if the pip install works if you prepend the domain name with `www.`?

For example `pip3 install natten==0.17.3 -f https://www.shi-labs.com/.....`

**Comment by alihassanijr** [comment]
Looks like we had a DNS issue, which is resolved now.

`shi-labs.com` should be coming back for everyone, and if not, please either allow some time for your DNS cache to update or clear it manually.

Apologies again for the inconvenience.

**Comment by alihassanijr** [comment]
Issue's been resolved. Closing.
