### ISSUE TITLE
How to build wheel with MSVC on windows

### ISSUE THREAD

**Issue by lldacing** [SHI-Labs/NATTEN#181]
I successfully installed natten0.17.3+torch2.5.0 with MSVC, just get a egg file, but I have many envs, how to build a whl file.

**Comment by lldacing** [comment]
I got it

**Comment by chensyo** [comment]
> I got it

Could you please tell me how to do it?

**Comment by lldacing** [comment]
> 
> 
> 
> 
> > I got it
> 
> Could you please tell me how to do it?

https://huggingface.co/lldacing/NATTEN-windows

I build some wheels, and record how to do

**Comment by chensyo** [comment]
Thanks for your work, I have downloaded it, but I still want to know how to build the WHL file myself

**Comment by chensyo** [comment]
> > > > I got it
> > > 
> > > 
> > > Could you please tell me how to do it?
> > 
> > 
> > https://huggingface.co/lldacing/NATTEN-windows
> > I build some wheels, and record how to do
> 
> I did the same thing yesterday. Why did I end up with a .egg file in the dist folder?

I see, I need to change this batch file to build, it was originally installed Thanks
