### ISSUE TITLE
An error occurred when using the get_flops method of natten

### ISSUE THREAD

**Issue by tpbreak** [SHI-Labs/NATTEN#183]
I used the following code to calculate the model's parameter count:
  ```
from natten.flops import get_flops
    model = model.cuda(gpu)
    x = [torch.zeros(1, 3, 480, 640, dtype = torch.float32).cuda(gpu), torch.zeros(1, 3, 480, 640, dtype = torch.float32).cuda(gpu)]
    model.eval()
    flop_ctr = get_flops(model, x)
```
However, the following error occurred in the code:
```
line 101, in forward
    fuse_rgb = na2d(
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/functional.py", line 1734, in na2d
    tiling_config_forward, tiling_config_backward = autotune_fna(
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/autotuner/__init__.py", line 178, in autotune_fna
    best_backward_config = get_default_tiling_config_for_fna_backward(
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/autotuner/fna_backward.py", line 151, in get_default_tiling_config_for_fna_backward
    assert len(spatial_extent) == na_dim and all(
AssertionError
```

I checked the intermediate outputs of the function and found that the .shape return value in the code ` spatial_extent = tuple(x for x in input_tensor.shape[1 : na_dim + 1])` of the function `get_default_tiling_config_for_fna_backward` in is torch.int64 instead of the expected int.I don't know how the error occurred, as everything was fine when the model was being trained.

**Comment by alihassanijr** [comment]
Thank you for bringing this to our attention. I'll start a patch for this soon, but since I can't reproduce the issue, would you mind testing the patch before we merge it and confirm that it fixes your issue?

**Comment by tpbreak** [comment]
Thank you for addressing this. I'd be happy to test the patch and confirm if it resolves the issue.

**Comment by tpbreak** [comment]
My natten version is 0.17.1+torch230cu118, and my Python version is 3.10. I hope this helps you reproduce the issue.

**Comment by alihassanijr** [comment]
Could you try directly replacing the file in question like this and see if it works?

```
wget https://raw.githubusercontent.com/alihassanijr/NATTEN-Torch/refs/heads/fix-autotuner-shape-checks/src/natten/autotuner/fna_backward.py

cp fna_backward.py /data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/autotuner/fna_backward.py
```

Or alternatively you could just clone this branch and build from source:

https://github.com/alihassanijr/NATTEN-Torch/tree/fix-autotuner-shape-checks

But given how long building from source takes and that this is a python-side patch with no serious conflicts, it's pretty much unnecessary.

**Comment by tpbreak** [comment]
Thank you for providing the patch. I followed your instructions to replace the original Python file, but a new issue has arisen. 
```  
File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/flops.py", line 307, in get_flops
    return flop_ctr.total()
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/fvcore/nn/jit_analysis.py", line 248, in total
    stats = self._analyze()
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/fvcore/nn/jit_analysis.py", line 584, in _analyze
    op_counts = self._op_handles[kind](inputs, outputs)
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/flops.py", line 77, in fna_generic_flops
    assert hasattr(scalar_args, "__len__") and len(scalar_args) == 5
AssertionError```

**Comment by alihassanijr** [comment]
Thank you -- I found a few more bugs, and #185 should resolve all of them.

Could you kindly try [that branch](https://github.com/alihassanijr/NATTEN-Torch/tree/fix-shape-checks-and-flop-counter) and see if it solves your issue?

With this one, you might want to replace all `.py` files in your local NATTEN install (no need to build from source, given that libnatten hasn't changed in a while).

A quick way to do that is to just clone the branch locally:

```bash
git clone https://github.com/alihassanijr/NATTEN-Torch NATTEN-fix

cd NATTEN-fix

git checkout fix-shape-checks-and-flop-counter
```

And then copy paste all python sources (from `NATTEN-fix/`):

```bash

for x in src/natten/**/*.py;do;y=${x/src\/natten\//};z="/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/$y";echo "Copying $x -> $z"; cp $x $z ;done

```

**Comment by tpbreak** [comment]
Thank you for your continued efforts to fix the issues; I really appreciate it! However, after trying the suggested branch and replacing all the .py files in my local NATTEN installation as instructed, I’m still encountering some problems.
```File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/flops.py", line 357, in get_flops
    return flop_ctr.total()
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/fvcore/nn/jit_analysis.py", line 248, in total
    stats = self._analyze()
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/fvcore/nn/jit_analysis.py", line 584, in _analyze
    op_counts = self._op_handles[kind](inputs, outputs)
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/flops.py", line 50, in fna_generic_flops
    len(output_shapes) == 2
AssertionError: Expected exactly 2 outputs (attention output, and LSE), got 1 ```

**Comment by tpbreak** [comment]
Thank you for your continued efforts to fix the issues; I really appreciate it! However, after trying the suggested branch and replacing all the .py files in my local NATTEN installation as instructed, I’m still encountering some problems.
```
File` "/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/flops.py", line 357, in get_flops
    return flop_ctr.total()
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/fvcore/nn/jit_analysis.py", line 248, in total
    stats = self._analyze()
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/fvcore/nn/jit_analysis.py", line 584, in _analyze
    op_counts = self._op_handles[kind](inputs, outputs)
  File "/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/flops.py", line 50, in fna_generic_flops
    len(output_shapes) == 2
AssertionError: Expected exactly 2 outputs (attention output, and LSE), got 1
```

**Comment by alihassanijr** [comment]
That's strange. It looks like as if `/data/miniconda3/envs/work1/lib/python3.10/site-packages/natten/functional.py` is still the old one. Could you try removing it, and copying `NATTEN-fix/src/natten/functional.py` in its place again?

If that doesn't work, could you try just building NATTEN from source?
If you have CUDA toolkit, all you'd need to do is to `cd` into `NATTEN-fix/` and run `make`.

**Comment by tpbreak** [comment]
Alright, I will check if all the .py files have been replaced correctly.

**Comment by alihassanijr** [comment]
@tpbreak I'll go ahead and merge the PR for now. Feel free to reopen the issue if things don't work on your end, but they should as long as you try and build NATTEN from source, or wait for the next release.
