### ISSUE TITLE
Wheel file for torch 2.0  (cpu/cu117/cu118)

### ISSUE THREAD

**Issue by ydshieh** [SHI-Labs/NATTEN#19]
Dear NATTEN author/team,

`torch 2.0` is going to be released soon (I believe it is this week). I am wondering if there are already wheel files for `natten` with `torch 2.0`, or there will be such wheel files soon after the `torch 2.0` release.

Thank you 🤗

**Comment by alihassanijr** [comment]
Hello and thank you for your interest,

Yes, once a stable torch release is out we will try and build wheels for that version and make the necessary changes to support it.

**Comment by alihassanijr** [comment]
Closing this since the new release supports torch 2.0 (cpu/cu11.7/cu11.8).
Feel free to open it back up if that is not the case.
