### ISSUE TITLE
`natten` 0.14.5 (CPU) issue regarding `natten2dqkrpb`

### ISSUE THREAD

**Issue by ydshieh** [SHI-Labs/NATTEN#23]
Dear NATTEN author(s)/team:

Since `0.14.5`, our CI (`transformers`) encounters a problem with `natten2dqkrpb`, which mentions `missing 1 required positional argument: 'dilation'`. With `0.14.4`, there is no such problem.

I can try to provide a (short) code snippet (without using the testing code in `transformers`), but I am wondering if there is a breaking change introduced in `natten==0.14.5`. Thank you :-)

Here is the error message we got
```code
        # Compute NA between "query" and "key" to get the raw attention scores, and add relative positional biases.
>       attention_scores = natten2dqkrpb(query_layer, key_layer, self.rpb, 1)
E       TypeError: natten2dqkrpb() missing 1 required positional argument: 'dilation'
```

**Comment by alihassanijr** [comment]
Hello,

It's because the new build makes RPB optional. I'd have to start a pull request to transformers to resolve that.

**Comment by ydshieh** [comment]
Thank you a lot, @alihassanijr ❤️

**Comment by alihassanijr** [comment]
Started PR:

https://github.com/huggingface/transformers/pull/22229

**Comment by alihassanijr** [comment]
Closing this since I believe the PR solved the issue. 
Feel free to open it back up if that is not the case.
