### ISSUE TITLE
Unexpected output shape if query has a different shape

### ISSUE THREAD

**Issue by wdeng** [SHI-Labs/NATTEN#25]
Hi,

I'm trying to use it for 1D cross attentions. But it seems the output shape doesn't not align with the expected shape. Any ideas?

```
from natten.functional import natten1dav, natten1dqkrpb
from torch import nn


q = torch.randn(2, 10, 64, 32)
k = torch.randn(2, 10, 100, 32)
v = torch.randn(2, 10, 100, 32)

# with Natten
attn = natten1dqkrpb(q, k, None, 15, 1)
attn = attn.softmax(dim=-1)
print('attention shape', attn.shape, 'output shape: ', natten1dav(attn, v, 15, 1).shape)

# expected shape
attn = torch.randn(2, 10, 64, 100)
print('attention shape', attn.shape, 'output shape: ', (attn@v).shape)
```

output shapes:
```
attention shape torch.Size([2, 10, 64, 15]) output shape:  torch.Size([2, 10, 100, 32])
attention shape torch.Size([2, 10, 64, 100]) output shape:  torch.Size([2, 10, 64, 32])
```

**Comment by alihassanijr** [comment]
Hello and thank you for your interest.

This is pretty much expected, because Neighborhood Attention is a restricted **self attention** pattern, and therefore only defined for cases where the query and key-value pair are of similar spatial size.

It is undefined for cross attention unless one defines a mapping between the query and key-value space.

**Comment by wdeng** [comment]
I see. This makes sense.

**Comment by Gutianpei** [comment]
> Hello and thank you for your interest.
> 
> This is pretty much expected, because Neighborhood Attention is a restricted **self attention** pattern, and therefore only defined for cases where the query and key-value pair are of similar spatial size.
> 
> It is undefined for cross attention unless one defines a mapping between the query and key-value space.
> 
> To be very clear: do not try and feed the functions queries and key-value pairs of different spatial sizes -- all backend functions and kernels are written based on the assumption that sequence lengths (1D) / feature map sizes (2D) are identical. If you don't, you will get unexpected results because the kernel launches will either fail, result in an illegal memory access, or produce incorrect outputs.

Do you plan to add support for cross attention?

**Comment by alihassanijr** [comment]
As the previous message indicates, it is not possible to restrict attention without assuming the query and context sets are identical (self attention). Therefore it is not possible to define neighborhood attention for cross attention. It is not a matter of implementation; it just doesn't make sense in theory.
