### ISSUE TITLE
NATTEN is not compiled with CUDA!

### ISSUE THREAD

**Issue by TaNo0** [SHI-Labs/NATTEN#34]
Thanks for your outstanding work. I'm currently trying to implement natten in my project, but I've come across an issue:

>   File "/data/Projects/NATTEN/env_nat/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/data/Projects/NATTEN/env_nat/lib/python3.8/site-packages/natten/natten2d.py", line 91, in forward
>     attn = natten2dqkrpb(q, k, self.rpb, self.kernel_size, self.dilation)
>   File "/data/Projects/NATTEN/env_nat/lib/python3.8/site-packages/natten/functional.py", line 186, in natten2dqkrpb
>     return NATTEN2DQKRPBFunction.apply(query, key, rpb, kernel_size, dilation)
>   File "/data/Projects/NATTEN/env_nat/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 118, in decorate_fwd
>     return fwd(*args, **kwargs)
>   File "/data/Projects/NATTEN/env_nat/lib/python3.8/site-packages/natten/functional.py", line 119, in forward
>     attn = _C.natten2dqkrpb_forward(query, key, rpb, kernel_size, dilation)
> RuntimeError: NATTEN is not compiled with CUDA! Please make sure you installed correctly by referring to shi-labs.com/natten.

Here are the versions of the corresponding packages:

> natten            0.14.6 
> torch             1.11.0+cu102 
> 
> Python  3.8.10
> torch.__version__  '1.11.0+cu102'
> torch._C._cuda_getCompiledVersion()  10020
> 
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Wed_Oct_23_19:24:38_PDT_2019
> Cuda compilation tools, release 10.2, V10.2.89

natten is installed with: 

> pip3 install natten -f https://shi-labs.com/natten/wheels/cu102/torch1.11.0/index.html

Could you please help me with this?

**Comment by alihassanijr** [comment]
Hello and thank you for your interest.

The URL you used in the pip command is incorrect. It's `torch1.11` not `torch1.11.0`.
Please try uninstalling natten and reinstall with this:

```
pip3 install natten -f https://shi-labs.com/natten/wheels/cu102/torch1.11/index.html 
```

**Comment by TaNo0** [comment]
It's working well. Thanks for your help.
