### ISSUE TITLE
pytorch version for latest natten

### ISSUE THREAD

**Issue by lcxsjtu** [SHI-Labs/NATTEN#40]
Thank you for your great work! May I ask if Pytorch 1.10.1 can install the latest version of NATTEN with GEMM? And does it necessarily require a Python version greater than 3.8? Is 3.7 okay? If there is any other strict version requirement that differ from the previous Natten version, please also tell me, really appreciate it!

**Comment by alihassanijr** [comment]
Thank you for your interest.
The minimum requirements are Python >= 3.7, Torch  >= 1.8.

To run the latest GEMM kernels, you also need to make sure you're running CUDA 11 or above (same goes for your torch, make sure it was compiled with CUDA 11 or above).

You also need to make sure your GPU compute capability is 8.0 or higher, or in other words, your GPU architecture must be Ampere, Ada Lovelace, or Hopper.

Once you successfully compile, you can check whether or not NATTEN was compiled with GEMM kernels with the following command:

```python
import natten

# Whether NATTEN with CUDA was built with the new GEMM kernels
print(natten.has_gemm())
```

If you meet the requirements, but are either unable to build successfully, or `has_gemm` is False, please let us know.

**Comment by yifanlu0227** [comment]
I build with Python=3.7, torch=1.10.1 and cuda=11.4 successfully, but with some slight modification:

In [setup.py](https://github.com/SHI-Labs/NATTEN/blob/59c27220259c992db2f599d619c71ab12e83fb55/setup.py#L37), torch 1.10.1 have no `IS_MACOS`, so I just set `IS_MACOS` to 0 on my linux machine.

In [csrc/CMakeLists.txt](https://github.com/SHI-Labs/NATTEN/blob/59c27220259c992db2f599d619c71ab12e83fb55/csrc/CMakeLists.txt#L8-L17), I reduce the version requirement for Python and CUDA to my version.

**Comment by alihassanijr** [comment]
Thank you for bringing this to our attention, the requirements in the cmake file are incorrect, I'll correct those soon (the python 3.8 and CUDA 11.8.)

As for `IS_MACOS`, it's just a global constant imported from torch, which should correctly detect whether or not it's a macos device, so you shouldn't worry about that.

But since you had a successful compile, you could try running the unit tests by running `make test` from the main directory, and if those pass (and no tests are skipped; we skip testing the GEMM kernels when they are not available), you should be using the new faster kernels by default.

Note that we also include methods that allow you to turn the new optimizations off:

```python
from natten import enable_gemm_na, enable_tf32, disable_gemm_na, disable_tf32

disable_tf32() # Turn off using TF32 instead of Float32 -- only available in GEMM kernels
disable_gemm_na() # Turn off using GEMM kernels entirely


enable_gemm_na() # Enable GEMM kernels
enable_tf32() # Enable TF32 for GEMM kernels
```

If it is not too much trouble, I would be interested in seeing the log from your running of unittests:

```
make test 2>&1 | tee test_out.txt
```

**Comment by yifanlu0227** [comment]
It is perfect. @alihassanijr 
```
Running unit tests
python -m unittest discover -v -s ./tests
test_autograd_cpu (test_na1d.NA1DTests) ... ok
test_autograd_cuda_gemm (test_na1d.NA1DTests) ... ok
test_autograd_cuda_naive (test_na1d.NA1DTests) ... ok
test_cpu_vs_cuda (test_na1d.NA1DTests) ... ok
test_autograd_cpu (test_na2d.NA2DTests) ... ok
test_autograd_cuda_gemm (test_na2d.NA2DTests) ... ok
test_autograd_cuda_naive (test_na2d.NA2DTests) ... ok
test_autograd_cuda_tiled (test_na2d.NA2DTests) ... ok
test_cpu_vs_cuda (test_na2d.NA2DTests) ... ok
test_autograd_cpu (test_na3d.NA3DTests) ... ok
test_autograd_cuda (test_na3d.NA3DTests) ... ok
test_cpu_vs_cuda (test_na3d.NA3DTests) ... ok

----------------------------------------------------------------------
Ran 12 tests in 135.381s

OK
```

**Comment by alihassanijr** [comment]
Thanks! That helps a lot.

We should be rolling out a second set of changes in the coming weeks that will hopefully bring the repository back to normal. Normal meaning those with even older GPUs that we support now will be able to build with as many features as we can support for their hardware, and of course bringing back the ability to build fat binaries will let us roll this out over pypi again with wheels.

In addition to those, I'll push the script I typically use to benchmark performance, which should let everyone try any problem size and measure the latency with different kernels; this would be useful if you're trying to either confirm that you have the right kernels and setup, or if you're just curious about the difference in latency given your specific problem size.

But thanks a lot again to @yifanlu0227 for verifying it worked out on your end.

**Comment by lcxsjtu** [comment]
Thanks for your reply and discussion! Looking forward to your progress~

**Comment by alihassanijr** [comment]
#81 Added profilers for NA1D and NA2D under `tools/`. They not only benchmark latency from each op, but also print out whether a GEMM or naive kernel was run, and if the former, what architecture it was targeting.

Closing this now, but feel free to reopen if there's anything else.
