### ISSUE TITLE
Code details about the neighborhood attention

### ISSUE THREAD

**Issue by jamesben6688** [SHI-Labs/NATTEN#45]
Hi Ali,

I was reading the details of neighbor attention. However, I only find the code snippet in `NATTEN/csrc/src/pytorch/na2d.cpp` (line 73):

`
auto attn = torch::empty({batch_size, heads, height, width, kernel_size * kernel_size}, query.options());
DISPATCH_DEVICE(query.device(), na2d_qk_forward,
        query,
        key,
        bias,
        attn,
        batch_size, heads, height, width, dim,
        kernel_size, dilation);
return attn;
`

seems like defined an empty attention array and return it?

May I know where the attention score between the query and key is computed and where the rpb is added?

**Comment by alihassanijr** [comment]
Hello and thank you for your interest.

First off, `DISPATCH_DEVICE` is what calls the the correct kernel, which is responsible for computing attention weights.
Secondly, all kernels are templates here, and naturally placed into headers and not source files. Source files are auto-generated to allow us (and in the future users) to minimize compile time by maximizing parallelism by dividing the instantiations into multiple source files.

I'd note there's no single implementation of NA (that's kind of the whole point of NATTEN). 
If you want to look at the CPU kernels, please refer to [csrc/include/natten/cpu/naive](https://github.com/SHI-Labs/NATTEN/tree/main/csrc/include/natten/cpu/naive) where you'll find header files for each op/dimensionality combination.

Relative positional biases are fused into the op responsible for QK, which is pointwise neighborhood.

So if you want to look at the CPU implementation of QK+rpb (NA2d), you should find it under [csrc/include/natten/cpu/naive/pointwise_neighborhood_2d.hpp](https://github.com/SHI-Labs/NATTEN/blob/main/csrc/include/natten/cpu/naive/pointwise_neighborhood_2d.hpp).

Please let me know if you have any more questions.

**Comment by alihassanijr** [comment]
Closing this now; feel free to reopen if you have more questions.
