### ISSUE TITLE
CUDA version (12.0)

### ISSUE THREAD

**Issue by Ray-MS** [SHI-Labs/NATTEN#46]
Why CUDA version (12.0) is not allowed?

Pytorch 11.8 allows the usage of CUDA 12.0 drivers and currently has no compatibility issues.

**Comment by alihassanijr** [comment]
CUDA 12 is supported.

**Comment by alihassanijr** [comment]
Closing this now. If you're having an issue building or installing NATTEN, feel free to reopen this.
