### ISSUE TITLE
About the dot product between q and k

### ISSUE THREAD

**Issue by davidnvq** [SHI-Labs/NATTEN#48]
Hello authors, thank you for releasing the great code base for computing Neighbor Attention.
I am trying to use the lib for computing the dot product between q and k to get the unnormalized attention scores.

Below is my code for reproducing the result. 
```python
import torch
from natten.functional import natten2dqk

H = 3
W = 3
q = torch.tensor(
    [[0., 1., 2.],
     [3., 4., 5.],
     [6., 7., 8.]])

k = torch.tensor(
    [[8., 5., 6.],
     [2., 3., 4.],
     [1., 6., 2.]])

q = q.view(1, 1, H, W, 1)
k = k.view(1, 1, H, W, 1)

attention = natten2dqk(
    query=q,
    key=k,
    kernel_size=2,
    dilation=0,
)
print(attention.long().squeeze())

"""attention = 
 tensor([[[ 0,  0,  0,  0],
          [ 8,  8,  8,  8],
          [16, 16, 16, 16]],
 
         [[24, 24, 24, 24],
          [32, 32, 32, 32],
          [40, 40, 40, 40]],
 
         [[48, 48, 48, 48],
          [56, 56, 56, 56],
          [64, 64, 64, 64]]]))
"""
```

I think the intuition is that we will compute the dot product between every entry in the `q` with the neighbor entries of `k` in the window of `kernel_size x kernel_size`.

For example, the first inner row of `attention` output is computed:
```python
# in the first row of out
# [0 * 8, 0 * 5, 0 * 2, 0 * 3]
# -> [ 0,  0,  0,  0]
```

For the second inner row of `attention`:
```python
# in the second row
# [1 * 5, 1 * 6, 1 * 3, 1 * 4]
# -> [ 5,  6,  3,  4]
# But we got [8, 8, 8, 8]?

# ... similar for other attention rows.
```
I know that my intuition would definitely wrong. May you correct me via this simple code?
Thank you so much beforehand!

**Comment by davidnvq** [comment]
When the `kernel_size` = 1, the above intuition seems correct:
```python
attention = natten2dqk(
    query=q,
    key=k,
    kernel_size=1,
    dilation=0,
)
print(attention.long().squeeze())

tensor([[ 0,  5, 12],
        [ 6, 12, 20],
        [ 6, 42, 16]])
```
May you kindly explain the correct intuition when `kernel_size > 1` (e.g., `kernel_size = 2` as above)?

**Comment by alihassanijr** [comment]
Hello and thank you for your interest,

Neighborhood attention is only defined for odd-sized kernel sizes greater than 1 (i.e. 3, 5, 7, 9, and so on)
Neighborhood attention with kernel size 1 == linear projection.

The API should block invalid kernel sizes, and not just the frontend, and it seems like you're using the op directly (which is fine), but because of the issue in the API, you're just not getting an error.

What you're doing is correct in order to produce unnormalized attention weights.

However, dilation=0 is incorrect (again there should've been an API error; I'll try to fix it and merge today.)
Dilation=1 means no dilation, similar to conv.

**Comment by davidnvq** [comment]
Thanks for getting back to me. You're right, I'll close the issue now. Just to keep a reference for others, here's the correct API output:
```python
import torch
from natten.functional import natten2dqk

H = 3
W = 3
q = torch.tensor(
    [[0., 1., 2.],
     [3., 4., 5.],
     [6., 7., 8.]])

k = torch.tensor(
    [[8., 5., 6.],
     [2., 3., 4.],
     [1., 6., 2.]])

q = q.view(1, 1, H, W, 1)
k = k.view(1, 1, H, W, 1)

attention = natten2dqk(
    query=q,
    key=k,
    kernel_size=3,
    dilation=1,
)
print(attention.long().squeeze())

tensor([[[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 8,  5,  6,  2,  3,  4,  1,  6,  2],
         [16, 10, 12,  4,  6,  8,  2, 12,  4]],

        [[24, 15, 18,  6,  9, 12,  3, 18,  6],
         [32, 20, 24,  8, 12, 16,  4, 24,  8],
         [40, 25, 30, 10, 15, 20,  5, 30, 10]],

        [[48, 30, 36, 12, 18, 24,  6, 36, 12],
         [56, 35, 42, 14, 21, 28,  7, 42, 14],
         [64, 40, 48, 16, 24, 32,  8, 48, 16]]])
```
