### ISSUE TITLE
module 'natten' has no attribute 'has_cuda'

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [SHI-Labs/NATTEN#52]
Hi!

Thanks for sharing the code.
I have install successfully with NATTEN extension, and the modules, like NeighborhoodAttention2D, can be imported

However, whenever I type 
```
import natten
print(natten.has_cuda())
```
It always return "module 'natten' has no attribute 'has_cuda'".

Does that mean I am not using the extension to acclerate the operation?
Thanks a lot.

**Comment by alihassanijr** [comment]
Thank you for your interest.
You probably installed the latest release (i.e. through pip), which is very different from the main branch, and the `has_cuda` constant, along with all other constants were only introduced a few commits back. 

As long as you can run unit tests, or try to run any module/op with CUDA tensors, you should be good to go.

However, if you're interested in the new kernels, you'll need to build NATTEN from source. The reason we haven't pushed a release yet is that I still have to figure out the best way to build fat binaries in the new build, and that is necessary for building wheels.

To install NATTEN from source, first remove the existing package, then clone the repository, and follow the instructions on building from source in the README.

Note: you'll only be able to use the new kernels if your GPU architecture is Volta or newer. If it is not, unfortunately the best option for you would be the latest release (what you have right now.)

**Comment by FireWallDragonDarkFluid** [comment]
Crystal clear, thank you.
