### ISSUE TITLE
Support for different Kernel dimensions for 2d

### ISSUE THREAD

**Issue by Daniel63656** [SHI-Labs/NATTEN#55]
Are you planning for supporting tuples for 2d kernels?

**Comment by alihassanijr** [comment]
We originally were, and it is technically possible for our naive kernels. However, our GEMM kernels have to tie kernel size to tile size, and as a result we don't yet have a reliable solution for that.

I can try to have naive kernels support it, but performance would be very limited compared to GEMM kernels.

**Comment by Daniel63656** [comment]
It would be great to have the option
