### ISSUE TITLE
How can see the details of natten's attention score calculation (q · k)

### ISSUE THREAD

**Issue by namespacedoyouknow** [SHI-Labs/NATTEN#59]
Sorry to bother you during the weekend.
This is a really nice work, but I would like to ask some questions:
First I want to know how this statement works:
`from natten import _C`
Is this the specific implementation of importing natten from a dynamic link library？
I also want to know how I can see the specific calculation details of the attention score, which cannot be displayed to me in Pycharm, like this:
`attn = _C.natten2dqkrpb_forward(query, key, rpb, kernel_size, dilation)`

`def natten2dqkrpb_forward(arg0, arg1, arg2, torch_Tensor=None, *args, **kwargs): # real signature unknown; NOTE: unreliably restored from __doc__ 
    """
    natten2dqkrpb_forward(arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: int, arg4: int) -> torch.Tensor
    
    NATTEN2DQK+RPB forward
    """
    pass`
_ C. The header annotation of the py file is:
`
# encoding: utf-8
# module natten._C
# from /mnt/c/Users/zzz/AppData/Local/JetBrains/PyCharm2021.3/remote_sources/380714796/-89893896/natten/_C.cpython-38-x86_64-linux-gnu.so
# by generator 1.147
# no doc
# no imports
`
What should I do if I want to know the specific attention score calculation details? 
Looking forward to receiving your reply very much！

**Comment by alihassanijr** [comment]
Thank you for your interest.

_C references the C library. 

To see the implementation, please refer to the library source and navigate according to device (`cpu` or `cuda`) and implementation (`naive`, `tiled` or `gemm`.)

Please refer to either the [NAT paper](https://openaccess.thecvf.com/content/CVPR2023/html/Hassani_Neighborhood_Attention_Transformer_CVPR_2023_paper.html) or [this report](https://www.cs.uoregon.edu/Reports/AREA-202307-Hassani.pdf) on why none of this is implemented in Python.
