### ISSUE TITLE
Pure pytorch version

### ISSUE THREAD

**Issue by KexianShen** [SHI-Labs/NATTEN#60]
Great work!

I wonder is there pure pytorch version of natten, because some embedded devices do not support cuda.

**Comment by alihassanijr** [comment]
Thank you for your interest.

Please refer to either the [NAT paper](https://openaccess.thecvf.com/content/CVPR2023/html/Hassani_Neighborhood_Attention_Transformer_CVPR_2023_paper.html) or [this report](https://www.cs.uoregon.edu/Reports/AREA-202307-Hassani.pdf) on why none of this is implemented in Python.
