### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Z-2148** [SHI-Labs/NATTEN#70]
Hello, I would like to ask this error is because of the installation of natten problem?
AttributeError: module 'natten._C' has no attribute 'na2d_qk_forward'

**Comment by alihassanijr** [comment]
You're not building NATTEN. Please refer to the README on how to build from source, or use the link to our website to install via pip. NATTEN is not a pure python package.

Closing this, but feel free to reopen or post comments if you still have questions.

**Comment by alihassanijr** [comment]
See #65 for more.

**Comment by Z-2148** [comment]
@alihassanijr
Hello.
I installed natten using this pip command, but still have this error.
pip3 install natten -f https://shi-labs.com/natten/wheels/cu118/torch2.0.0/index.html 
AttributeError: module 'natten._C' has no attribute 'na2d_qk_forward'
