### ISSUE TITLE
Inquiry about NATTEN Compatibility with New Google Colab Version

### ISSUE THREAD

**Issue by Miiitiii** [SHI-Labs/NATTEN#73]
First and foremost, I would like to express my sincere gratitude for the incredible work you do on the NATTEN project. Your dedication and contributions have been invaluable to the community.

I am writing to inquire about the compatibility of NATTEN with the latest Google Colab version. In the new Colab version, the Torch version is updated to 2.1.0, and the CUDA version is now 12.1. I am eager to use NATTEN in this environment and would like to know if there are plans to upgrade NATTEN to support these new versions.

If possible, could you please provide an estimated timeline for when NATTEN might be upgraded to be compatible with Torch 2.1.0 and CUDA 12.1? This information would be extremely helpful as I plan my work.

**Comment by alihassanijr** [comment]
Hello and thank you for your interest!

NATTEN should be compatible with those builds, as long as it's built from source.
The reason why we haven't been able to push out new releases is the new build system and how difficult it's become to build fat binaries (that support multiple GPU architectures).
It's at the top of our priorities and I'll try to get that fixed soon.

That said, I still think you might be able to build from source on Colab. I'll try that later today to confirm.

**Comment by alihassanijr** [comment]
Yes, it is very easy to build NATTEN on Colab. Just might take a 10 - 15 minutes.

https://colab.research.google.com/drive/1w_VAIfkffn2AuWDKWFPH0wlXQ_uGSSSP?usp=sharing

**Comment by Miiitiii** [comment]
thank you for your kindly response. i appreciate you and your work. 

good luck

**Comment by Miiitiii** [comment]
thank you for your kindly response. i appreciate you and your work.

good luck

**Comment by immengzi** [comment]
To be honest, I spent over 60 minutes in building NATTEN in Colab:(
My plan is Colab Pro, and typeof runtime is T4 GPU with high raw.
![image](https://github.com/SHI-Labs/NATTEN/assets/95157017/efa477da-cb71-4c3d-8a4d-46bc01f7f56a)

**Comment by alihassanijr** [comment]
@immengzi First off 20 minutes was an estimate from almost 5 months ago. We've almost quadrupled in size since, so naturally build time has grown, and it'll take more than half an hour if you're using a desktop CPU, let alone cloud.

BUT we've also pushed out a release very recently that packs all of our most recent features, so I really don't see the point in building NATTEN from source on Colab 🙂 .
