### ISSUE TITLE
Ubuntu 22.04, Nvidia 4090 Problem to setup

### ISSUE THREAD

**Issue by Chloe-jpg** [SHI-Labs/NATTEN#75]
"Hello, thank you for your excellent work. May I ask if this code can run on the environment with Ubuntu 22.04, Nvidia 4090, Python 12.1, and CUDA 11.5? Currently, I am unable to install it successfully from the library."
![image](https://github.com/SHI-Labs/NATTEN/assets/56851887/5bc85d13-0809-4f49-813f-88017aea81a0)

![image](https://github.com/SHI-Labs/NATTEN/assets/56851887/215e7f2d-dd76-43b8-87ac-312299c16dc0)

**Comment by Chloe-jpg** [comment]
![image](https://github.com/SHI-Labs/NATTEN/assets/56851887/ba2ed3fa-d9f4-4b90-8dcd-5f8967e8cba4)

**Comment by alihassanijr** [comment]
Could you please provide the full log file? If you used the `make` command to build, it should be in the same directory under `install.out`.

**Comment by Chloe-jpg** [comment]
Using pip 23.3.2 from /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/pip (python 3.8)
Obtaining file:///home/qi/Project/3DUX-Net/NATTEN
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  Building NATTEN with CUDA 117
  Building NATTEN for SM: 8.9
  Number of workers: 8
  running egg_info
  creating /tmp/pip-pip-egg-info-vnvbkdh3/natten.egg-info
  writing /tmp/pip-pip-egg-info-vnvbkdh3/natten.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-vnvbkdh3/natten.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-vnvbkdh3/natten.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-vnvbkdh3/natten.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-vnvbkdh3/natten.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-vnvbkdh3/natten.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-vnvbkdh3/natten.egg-info/SOURCES.txt'
  /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/dist.py:314: InformationOnly: Normalizing '0.14.7.dev' to '0.14.7.dev0'
    self.metadata.version = self._normalize_version(self.metadata.version)
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: packaging in /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages (from natten==0.14.7.dev0) (23.1)
Installing collected packages: natten
  Running setup.py develop for natten
    Running command python setup.py develop
    Building NATTEN with CUDA 117
    Building NATTEN for SM: 8.9
    Number of workers: 8
    running develop
    running egg_info
    creating src/natten.egg-info
    writing src/natten.egg-info/PKG-INFO
    writing dependency_links to src/natten.egg-info/dependency_links.txt
    writing requirements to src/natten.egg-info/requires.txt
    writing top-level names to src/natten.egg-info/top_level.txt
    writing manifest file 'src/natten.egg-info/SOURCES.txt'
    reading manifest file 'src/natten.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'src/natten.egg-info/SOURCES.txt'
    running build_ext
    -- The CXX compiler identification is GNU 11.4.0
    -- The CUDA compiler identification is NVIDIA 11.5.119
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Detecting CUDA compiler ABI info
    -- Detecting CUDA compiler ABI info - done
    -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
    -- Detecting CUDA compile features
    -- Detecting CUDA compile features - done
    -- Looking for C++ include pthread.h
    -- Looking for C++ include pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE
    -- Found CUDA: /usr/local/cuda (found suitable version "11.5", minimum required is "10.2")
    Building NATTEN with CUDA.
    -- Found Python: /home/qi/anaconda3/envs/imageSeg/bin/python3.8 (found suitable version "3.8.17", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed
    -- Found CUDA: /usr/local/cuda (found version "11.5")
    -- Caffe2: CUDA detected: 11.5
    -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
    -- Caffe2: CUDA toolkit directory: /usr/local/cuda
    -- Caffe2: Header version is: 11.5
    -- /usr/local/cuda/lib64/libnvrtc.so shorthash is 65f2c18b
    -- USE_CUDNN is set to 0. Compiling without cuDNN support
    -- Autodetected CUDA architecture(s):  8.6+PTX 8.6+PTX
    -- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
    CMake Warning at /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
      static library kineto_LIBRARY-NOTFOUND not found.
    Call Stack (most recent call first):
      /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
      CMakeLists.txt:50 (find_package)


    -- Found Torch: /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/torch/lib/libtorch.so
    Building NATTEN with GEMM kernels.
    CMAKE_CUDA_FLAGS_RELEASE: -O3 -DNDEBUG -Xcompiler -O3 --use_fast_math
    CUDA compiler: /usr/local/cuda/bin/nvcc
    NVCC executable: /usr/local/cuda/bin/nvcc
    Building NATTEN with CUTLASS-based GEMM kernels.
    GEMM kernels targeting SM 80
    Building NATTEN with FP16 support.
    Building NATTEN with BF16 support.
    Building NATTEN for the following architectures: 89
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/qi/Project/3DUX-Net/NATTEN/build/lib.linux-x86_64-cpython-38
    make[1]: 进入目录“/home/qi/Project/3DUX-Net/NATTEN/build/lib.linux-x86_64-cpython-38”
    make[2]: 进入目录“/home/qi/Project/3DUX-Net/NATTEN/build/lib.linux-x86_64-cpython-38”
    make[3]: 进入目录“/home/qi/Project/3DUX-Net/NATTEN/build/lib.linux-x86_64-cpython-38”
    make[3]: 离开目录“/home/qi/Project/3DUX-Net/NATTEN/build/lib.linux-x86_64-cpython-38”
    make[3]: 进入目录“/home/qi/Project/3DUX-Net/NATTEN/build/lib.linux-x86_64-cpython-38”
    [  9%] [32mBuilding CXX object CMakeFiles/natten.dir/autogen/src/cpu/naive/source_0.cpp.o[0m
    [  9%] [32mBuilding CXX object CMakeFiles/natten.dir/autogen/src/cpu/naive/source_1.cpp.o[0m
    [ 13%] [32mBuilding CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/1d/sm80/source_0.cu.o[0m
    [ 18%] [32mBuilding CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/1d/sm80/source_1.cu.o[0m
    [ 22%] [32mBuilding CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_0.cu.o[0m
    [ 27%] [32mBuilding CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_1.cu.o[0m
    [ 31%] [32mBuilding CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_2.cu.o[0m
    [ 36%] [32mBuilding CUDA object CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_3.cu.o[0m
    nvcc fatal   : Unsupported gpu architecture 'compute_89'
    nvcc fatal   : Unsupported gpu architecture 'compute_89'
    nvcc fatal   : Unsupported gpu architecture 'compute_89'
    make[3]: *** [CMakeFiles/natten.dir/build.make:104：CMakeFiles/natten.dir/autogen/src/cuda/gemm/1d/sm80/source_0.cu.o] 错误 1
    make[3]: *** 正在等待未完成的任务....
    make[3]: *** [CMakeFiles/natten.dir/build.make:118：CMakeFiles/natten.dir/autogen/src/cuda/gemm/1d/sm80/source_1.cu.o] 错误 1
    make[3]: *** [CMakeFiles/natten.dir/build.make:132：CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_0.cu.o] 错误 1
    nvcc fatal   : Unsupported gpu architecture 'compute_89'
    nvcc fatal   : Unsupported gpu architecture 'compute_89'
    nvcc fatal   : Unsupported gpu architecture 'compute_89'
    make[3]: *** [CMakeFiles/natten.dir/build.make:146：CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_1.cu.o] 错误 1
    make[3]: *** [CMakeFiles/natten.dir/build.make:160：CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_2.cu.o] 错误 1
    make[3]: *** [CMakeFiles/natten.dir/build.make:174：CMakeFiles/natten.dir/autogen/src/cuda/gemm/2d/sm80/source_3.cu.o] 错误 1
    In file included from /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                     from /home/qi/Project/3DUX-Net/NATTEN/csrc/./include/natten/cpu/naive/pointwise_neighborhood_2d.hpp:38,
                     from /home/qi/Project/3DUX-Net/NATTEN/csrc/autogen/src/cpu/naive/source_0.cpp:2:
    /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h: In function ‘scalar_t at::vec::vec_reduce_all(const Op&, at::vec::CPU_CAPABILITY::Vectorized<T>, int64_t) [with scalar_t = double; Op = natten::cpu::naive::PointwiseNeighborhood1D<double>::launch(double*, double*, double*, int, int, int, int, int, int)::<lambda(int, int)>::<lambda(Vec&, Vec&)>]’:
    /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:13:17: note: the ABI for passing parameters with 32-byte alignment has changed in GCC 4.6
       13 | inline scalar_t vec_reduce_all(
          |                 ^~~~~~~~~~~~~~
    make[3]: 离开目录“/home/qi/Project/3DUX-Net/NATTEN/build/lib.linux-x86_64-cpython-38”
    make[2]: *** [CMakeFiles/Makefile2:83：CMakeFiles/natten.dir/all] 错误 2
    make[2]: 离开目录“/home/qi/Project/3DUX-Net/NATTEN/build/lib.linux-x86_64-cpython-38”
    make[1]: *** [Makefile:91：all] 错误 2
    make[1]: 离开目录“/home/qi/Project/3DUX-Net/NATTEN/build/lib.linux-x86_64-cpython-38”
    /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/dist.py:314: InformationOnly: Normalizing '0.14.7.dev' to '0.14.7.dev0'
      self.metadata.version = self._normalize_version(self.metadata.version)
    /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/command/develop.py:39: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************

    !!
      easy_install.initialize_options(self)
    /home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/qi/Project/3DUX-Net/NATTEN/setup.py", line 213, in <module>
        setup(
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
        return distutils.core.setup(**attrs)
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
        super().run_command(command)
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/command/develop.py", line 33, in run
        self.install_for_development()
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/command/develop.py", line 108, in install_for_development
        self.run_command('build_ext')
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
        super().run_command(command)
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
        _build_ext.run(self)
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/qi/Project/3DUX-Net/NATTEN/setup.py", line 210, in build_extension
        subprocess.check_call(['make', f"-j{n_workers}"], cwd=self.build_lib)
      File "/home/qi/anaconda3/envs/imageSeg/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j8']' returned non-zero exit status 2.
    Current arch: 89
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/qi/anaconda3/envs/imageSeg/bin/python3 -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/qi/Project/3DUX-Net/NATTEN/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/qi/Project/3DUX-Net/NATTEN/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Chloe-jpg** [comment]
(imageSeg) (base) qi@test:~/Project/3DUX-Net/NATTEN$ conda list torch
# packages in environment at /home/qi/anaconda3/envs/imageSeg:
#
# Name                    Version                   Build  Channel
efficientnet-pytorch      0.7.1                    pypi_0    pypi
ema-pytorch               0.3.0                    pypi_0    pypi
pytorch-ignite            0.4.12                   pypi_0    pypi
pytorch-metric-learning   2.3.0                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
segmentation-models-pytorch 0.3.3                    pypi_0    pypi
torch                     2.0.0                    pypi_0    pypi
torch-summary             1.4.5                    pypi_0    pypi
torchaudio                2.1.1                    pypi_0    pypi
torchcam                  0.4.0.dev0               pypi_0    pypi
torchmetrics              1.2.0                    pypi_0    pypi
torchvision               0.15.1                   pypi_0    pypi
torchviz                  0.0.2                    pypi_0    pypi
(imageSeg) (base) qi@test:~/Project/3DUX-Net/NATTEN$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
(imageSeg) (base) qi@test:~/Project/3DUX-Net/NATTEN$ nvidia-smi
Fri Jan  5 20:17:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:06:00.0 Off |                  Off |
| 31%   33C    P8              18W / 450W |    316MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off | 00000000:07:00.0 Off |                  Off |
| 30%   32C    P8              18W / 450W |     16MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1830      G   /usr/lib/xorg/Xorg                          214MiB |
|    0   N/A  N/A      1995      G   /usr/bin/gnome-shell                         65MiB |
|    0   N/A  N/A      4691      G   /usr/local/sunlogin/bin/sunloginclient       16MiB |
|    1   N/A  N/A      1830      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+

**Comment by alihassanijr** [comment]
I think it's because your cuda compiler is 11.5; and the minimum CUDA version that supports SM89 (i.e. 4090) is 11.7.

Can you try upgrading your cuda toolkit?

I'm actually very surprised that torch is working for you; but it is possible that it's just the compiler that's outdated and not the libraries.

**Comment by Chloe-jpg** [comment]
It works！Thank you so much！
