### ISSUE TITLE
Torch atomicAdd in RPB backward FP16 kernel can fail

### ISSUE THREAD

**Issue by alihassanijr** [SHI-Labs/NATTEN#97]
RPB gradient kernels are all using torch atomics, which is not absolutely necessary in FP32, since as far as I recall, the torch atomic add was pretty similar in perf to the standard cuda one.

FP16 has always been tricky, because the standard cuda atomic add for `half` was just very slow (unlike `half2`; which is probably because the `half` one is using a slow CAS instruction).

The torch atomic add uses the `half2` atomic instruction by packing the value being added with a 0, which in theory should work as long as the pointer is correctly aligned. Even though this is not always the case (i.e. if heads aren't an even number), there still are very rare and very hard-to-reproduce cases where the atomic add ends up accessing and out of bounds address.

The only short-term solution that I can think of is forcing the RPB gradient kernels to run in FP32 and then cast the tensor (or split into two kernels). 

In the long run, RPB is just becoming a pain and not always used, so it might get dropped entirely as a feature.

**Comment by JCBrouwer** [comment]
I  would appreciate a better warning in the docs for this. This is also an issue for BF16.

Just spent a very long time debugging a `CUDA error: an illegal memory access was encountered` on my backward pass.

Had to add backward printing hooks all over the place to track down the actual source: `na3d_qk`.

Disabling RPB fixed it for me!

**Comment by alihassanijr** [comment]
Apologies for the inconvenience.

RPB's been a real pain from the very beginning of the project, but we've had to maintain it in order to continue supporting models like NAT/DiNAT and StyleNAT.
Given the issues, and the fact that it doesn't provide much of an advantage at scale, we're slowly starting to abandon the feature, and since #111 it has been turned off by default in the front end.

All that aside, you are right in that there should be warnings in NATTEN until the issue is resolved. I'll try and get either the FP32 fix or the warning in this week.

**Comment by alihassanijr** [comment]
Closing this now, but feel free to reopen if you come across this again.
